### ISSUE TITLE
Release 2024.1 M1 (2024.1.0)

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-bom#214]

**Comment by JohnNiang** [comment]
Hi @mp911de  and @schauder , I found the Spring Data Bom `2024.1.0-M1` disappeared in <https://repo.spring.io/ui/native/milestone/org/springframework/data/spring-data-bom/>. So I can not build my project with Spring Boot 3.4.0-M3, please see the following log:

```gradle
      > Could not resolve org.springframework.boot:spring-boot-dependencies:3.4.0-M3.
         > Could not parse POM https://repo.spring.io/milestone/org/springframework/boot/spring-boot-dependencies/3.4.0-M3/spring-boot-dependencies-3.4.0-M3.pom
            > Could not find org.springframework.data:spring-data-bom:2024.1.0-M1.
```

**Comment by ZheSun88** [comment]
i got the same error when using spring-boot `3.4.0-M3`

**Comment by mp911de** [comment]
That's fixed now.
