### ISSUE TITLE
spring-data-bom 2024.1.0-M1 version is not available

### ISSUE THREAD

**Issue by ZheSun88** [spring-projects/spring-data-bom#234]
when i am test my project by using the spring-boot,3.4.0-M3, it got the error that it cannot find the `spring-data-bom:2024.1.0-M1`
by checking the spring release repo, this version is not listed there. 
https://repo.spring.io/ui/native/milestone/org/springframework/data/spring-data-bom/

same issue has been mentioned https://github.com/spring-projects/spring-data-bom/issues/214#issuecomment-2424862068

**Comment by mp911de** [comment]
That's fixed now.
